### ISSUE TITLE
Luane

### ISSUE THREAD

**Issue by arxdsilva** [levpay/desafio#10]
https://github.com/LuaneASantos/Projeto-go

https://www.linkedin.com/in/luane-dos-santos-05961415a/

**Comment by matancredi** [comment]
Testes estão passando?
Não, porque eles precisam do seed do banco de dados e não é possível criá-lo, pois é necessário modificar o código.

A app roda? 
Ela executa na porta 8000, mas as migrações não rodam e o banco não é criado. Assim, não é possível testar os endpoints.

A app funcionaria em alguma cloud?
Não sem algumas modificações, pois não conseguimos rodar nem localmente.

A arquitetura de pacotes faz sentido?
Os pacotes usados são pertinentes à aplicação, mas podem ser organizados de uma forma melhor (sugestão: https://imasters.com.br/back-end/guia-de-estilo-para-pacotes-go)

Documentação das rotas está clara?
Sim

**Comment by matancredi** [comment]
Mandado para a candidata
