### ISSUE TITLE
Desafio Pedro

### ISSUE THREAD

**Issue by arxdsilva** [levpay/desafio#2]
https://github.com/pedrohcrisanto/testlevpay/

**Comment by arxdsilva** [comment]
# Avaliacao

Por se tratar de um perfil mais Junior não consideramos um grande empecilho os possíveis problemas específicos a Go, mas sim a falta de qualquer noção com relação ao design de uma aplicação no contexto de nuvem.

## Go
1. Nao possui de testes
2. Uso demasiado de `panic` em situacoes desnecessarias
3. Faltou checkar envs na inicializacao
4. Nao soube lidar com resultado vazio de uma busca
5. Ignorou certos retornos de erro

## Design
1. repeticao desnecessaria de codigo (ex: conexao com o banco)
2. faltou estruturar melhor os diversos pacotes necessarios para uma API
3. Nao lidou com logicas necessarias para o devido armazenamento dos dados da API externa (ex: quantidade de 'relatives')

**Comment by joelmdesouza** [comment]
@arxdsilva foi passado esse feedback para o Pedro?
